# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

#      - name: Setup Python
#        uses: actions/setup-python@v2.3.1
#        with:
#          python-version: '3.9'
#          architecture: 'x64'

#      - name: Cleanup
#        uses: rokibhasansagar/slimhub_actions@main

#      - name: Clean Up
#        run: |
#          docker rmi `docker images -q`
#          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
#          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
#          sudo apt update
#          sudo apt -y autoremove --purge
#          sudo apt clean

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
